name: Test Coverage
on:
  push:
    branches:
      - develop
      - dev

jobs:
  collect-coverage:
    name: Collect Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v2

      - name: Set Up Nightly llvm-tools-preview, with binutils and rustfilt
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: llvm-tools-preview
          install: cargo-binutils rustfilt
          cache: true
          cache-job-id: ${{ github.workflow }}-${{ github.job }}
          cache-hash: ${{ hashFiles('.github/workflows/coverage.yml') }}

      - name: Install Required Dependencies (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Run Tests and Collect Coverage
        run: bash ./coverage.sh

      - name: Upload Coverage data to Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/coverage.info
          flag-name: Unit
